# Use root/root as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  node:
    image: node:8-alpine
    container_name: node
    restart: always
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./workspace/myapp:/home/node/app
    expose:
      - "3000"
    command: "npm watch"
